export const homeCaroselImageWrapper: string;
export const homeCaroselImageWrapperImg: string;
export const homeCaroselTitle: string;
export const homeCaroselSubtitle: string;
export const homeCaroselSubtitleSpan: string;
export const homeCaroselOverlay: string;
export const homeCaroselDiscription: string;
export const homeCaroselDiscriptionSpan: string;
export const homeCaroselCardTitle: string;
